"""add confirm

Revision ID: 15fb3b449a2d
Revises: ce174428f199
Create Date: 2016-09-21 19:16:31.089990

"""

# revision identifiers, used by Alembic.
revision = '15fb3b449a2d'
down_revision = 'ce174428f199'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'comfirmed')
    ### end Alembic commands ###
