"""modify

Revision ID: 86a36f65164d
Revises: 15fb3b449a2d
Create Date: 2016-09-21 20:03:30.489633

"""

# revision identifiers, used by Alembic.
revision = '86a36f65164d'
down_revision = '15fb3b449a2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
